apollo-lhc/cm_mcu

common/smbus_units.c, common/smbus_units.h, projects/project2/ADCMonitorTask.c, projects/project2/CommandLineTask.c, projects/project2/FireFlyTask.c, projects/project2/Makefile, projects/project2/MonitorTask.c, projects/project2/MonitorTask.h, projects/project2/project2.c
Update for measuring FF temps, including CLI entry
=> Firefly dev

common/power_ctl.c, projects/project2/AlarmTask.c, projects/project2/CommandLineTask.c, projects/project2/FireFlyTask.c, projects/project2/MonitorTask.c, projects/project2/MonitorTask.h, projects/project2/PowerSupplyTask.c, projects/project2/Tasks.h, projects/project2/project2.c
- fix newlines to send \r\n everywhere, now tested with `screen` and seems to work. there is a weird issue where the CLI double-prints output in the case of long commands (`adc` and `help` at least have this issue)
- fix a bug in the firefly monitoring code where the values and names would get mis-associated. Also clean up the printout to make it easier to parse
- add a `version` command to the CLI
- buffer overwrite in task name handling
=> Cleanup and bugfixes

projects/cm_mcu/CommandLineTask.c
Added CLI command to restart MCU
=> Restart command

boot_loader/bl_config.h
Switch the boot loader from the FP UART to the Zynq UART.
=> switch to zynq uart for boot loader

projects/cm_mcu/ADCMonitorTask.c
=> Fix incorrect ADC channel mapping

projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/InterruptHandlers.c, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/SoftUartTask.c, projects/cm_mcu/Tasks.h, projects/cm_mcu/cm_mcu.c
Incorrect setting of the timer interrupt for the soft UART for the MCU->Zynq monitoring data path caused data corruption. This has been fixed. Some debugging software (currently ifdef'd out) is also included in this PR.
=> Fix bug in soft UART for MCU->ZYNQ data transfer

projects/cm_mcu/Makefile, projects/cm_mcu/Tasks.h, projects/cm_mcu/ZynqMonTask.c, projects/cm_mcu/cm_mcu.c
this fix adds two missing supplies and also gets rid of extra data that was being sent erroneously. 
Also rename the SoftUartTask to ZynqMonTask to describe what it does, not how it does it.
=> Zynq monitoring path: bug fix to address updated address table/missing data

.clang-format, common/utils.c, common/utils.h, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/PowerSupplyTask.c
Closes #60 
This PR fixes the bug that the supply mask for the failing supplies is too big to fit into the error logger data field (7 bits previously.) In this PR the bitfield is changed to 8 bits and the error logging for the supply mask now uses a continuation code.  Since the number of repeats is limited to 4 (2 bits) there was no reason to have 4 bits for that code.
Other changes include allowing up to 64 entries in the output of the error logger (previously on my recommendation this was limited to 25, but this meant that the additional error entries were effectively invisible.)
Other minor formatting changes.
=> Fix error handling for power supply mask

common/utils.c, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/FreeRTOSConfig.h, projects/cm_mcu/PowerSupplyTask.c, projects/cm_mcu/ZynqMonTask.c
* Ensure stale data gets marked as such for the zynq monitoring data path
* also try to fix the error logger for asserts
=> Ensure that NaNs and/or -55 (int) are sent when data is stale

.travis.yml, common/power_ctl.c, common/power_ctl.h, makedefs, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/FreeRTOSConfig.h, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/MonitorTask.c, projects/cm_mcu/MonitorTask.h, projects/cm_mcu/PowerSupplyTask.c, projects/cm_mcu/README.md, projects/cm_mcu/Tasks.h, projects/cm_mcu/cm_mcu.c
This change requires ECN001 and ECN002 (though strictly only ECN001). It initializes the LGA80D as recommended by the vendor.
=> Initialization code for LGA80D power supplies 

projects/cm_mcu/clocksynth.c
fixing the waiting time (1ms → 330 ms) between preamble/programing/postamble for clock synthesizer programming
=> fixing the waiting time for clock command

.clang-tidy, common/power_ctl.c, common/utils.c, projects/boot_loader/bl_startup_gcc.S, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/FireFlyTask.c, projects/cm_mcu/FreeRTOSConfig.h, projects/cm_mcu/startup_gcc.c
Minor code cleanups, including
- comment clarification
- change default UART to Zynq from front panel
- new default interrupt handler for boot loader which turns on red LED (not currently enabled)
=> Minor cleanups 

driverlib/cpu.c, driverlib/sysctl.c, makedefs, projects/Makefile, projects/boot_loader/bl_link.ld, projects/boot_loader/bl_main.c, projects/boot_loader/bl_startup_clang.S, projects/cm_mcu/Makefile, projects/cm_mcu/cm_mcu.ld, projects/cm_mcu/startup_clang.c
update the code base to allow a clang build to complete. 
**Note that the resulting binary has not been tested**
the main purpose of this compiler path is to allow building with clang and its better static code analysis tools and warnings compared to gcc.
=> Clang build

.gitattributes, common/i2c_reg.h, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/FireFlyTask.c, projects/cm_mcu/I2CCommunication.c, projects/cm_mcu/I2CCommunication.h, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/clocksynth.c, projects/cm_mcu/clocksynth.h, projects/cm_mcu/commands/I2CCommands.c
First attempt in merging `rev2b_eeprom` to `master` branch -- this is part of the fix of #123 issue, and the CLI for `i2cwr` and `i2crr` are working as expected.
=> Rev2b eeprom

projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/InitTask.c, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/MonitorI2CTask.c, projects/cm_mcu/MonitorI2CTask.h, projects/cm_mcu/Tasks.h, projects/cm_mcu/ZynqMonTask.c, projects/cm_mcu/cm_mcu.c, projects/cm_mcu/commands/BoardCommands.c, projects/cm_mcu/commands/SensorControl.c
* only do clock monitoring on Rev2 for now
* only init FF I/O expanders after power is up, and fix up semaphores here
* also fix a Rev2 bug on ZynqMonitorTask
=> Hotfix for issues running on Rev1

projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/InitTask.c, projects/cm_mcu/LocalTasks.c
Testing the CLI `loadclock` 0-4 on CM202 (FPGA-less board) after removing this hardcode and adjust semaphore scopes, and the following results look as expected:
```
% loadclock 0                                                                                                       
loadclock is programming clock r0a.                                                                                 
clock synthesizer with id r0a successfully programmed.                                                              
% loadclock 1                                                                                                       
loadclock is programming clock r0b.                                                                                 
clock synthesizer with id r0b successfully …
```
=> Fix hardcode in InitTask from issue #148 

projects/cm_mcu/CommandLineTask.c
issue : `loadclock` stuck when `cmpwrdown` but does the job when `cmpwrup` 
solution : we just add a check on this in a commandline code of a loadclock command. 
conclusion : yes, `cmpwrdown` was the issue and now loadclock will quite when pwr is off. 
note that this was tested on Apollo213 on 10/28/2022
=> require a check on 3.3V power supply for loadclock 

projects/cm_mcu/MonitorI2CTask.c
add a break in MONI2C whenever the argument reaches the last device and the power is still not on (to avoid infinite loop before giving a semaphore).
=> Debug apollo205

projects/cm_mcu/I2CCommunication.c, projects/cm_mcu/PowerSupplyTask.c, projects/cm_mcu/Tasks.h
I think this finally fixes the issue with apollo205. The fix adds a state to the power-control state machine that is between ON and OFF so we go from ON -> DOWN -> OFF. Other tasks can now see that the power is no longer ON but it is still ON long enough to allow the current set of tasks to complete, thereby avoiding the weird behavior where it appears that one of the I2C controllers goes into a loop where it continually fires an interrupt when power gets removed, thereby starving the rest of the MCU tasks of resources, which causes the CLI to lock up and the MCU to no longer respond to power-control requests.
=> add new 'powering down' state to PS state machine

projects/cm_mcu/PowerSupplyTask.c
Mistake that I didn't catch in PR #169
=> Bug fix: add 'DOWN' state to power control state machine strings

.github/workflows/c-cpp.yml
Fix clang in github actions CI
=> GitHub actions fix

projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/InitTask.c, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/MonitorI2CTask.c, projects/cm_mcu/MonitorTask.c, projects/cm_mcu/Semaphore.c, projects/cm_mcu/Semaphore.h, projects/cm_mcu/Tasks.h, projects/cm_mcu/commands/BoardCommands.c, projects/cm_mcu/commands/I2CCommands.c, projects/cm_mcu/commands/SensorControl.c, projects/cm_mcu/commands/SoftwareCommands.c
- replace xSemaphoreTake infinite loop by `acquireI2CSemaphore` 
- add a check of `xSemaphoreGetMutexHolder(s) == xTaskGetCurrentTaskHandle()` where s is the semaphore struct before  xSemaphoreGive 
- a few improvement such as removing misleading statement of "... tried releasing a semaphore we don't own.. " that does nothing if semaphore is not owned in the scope, and increasing maxtries in `acquireI2CSemaphore.`
Here is the test that indicates that the current code works as expected :
```
% loadclock 0                                                                                                                                                                       
loadclock is programming clock r0a. …
```
=> Add check to every Semaphore Take and Give 

common/utils.c, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/MonitorI2CTask.c, projects/cm_mcu/MonitorTask.c, projects/cm_mcu/Tasks.h, projects/cm_mcu/ZynqMonTask.c, projects/cm_mcu/commands/SensorControl.c
seems that some tasks' data are not being marked as stale when they should be. This tries to fix that.
=> Bug fix: update how stale data is handled for monitor tasks

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/c-cpp.yml, .github/workflows/codeql-analysis.yml, .github/workflows/format-commit.yml, .github/workflows/release.yml, .gitmodules, Makefile, README.md, projects/cm_mcu/Makefile
To make more uniform builds we now turn FreeRTOS into a submodule. This also makes for one less thing to download.
=> Turn FreeRTOS use into a submodule

projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/commands/SensorControl.c, projects/cm_mcu/commands/SensorControl.h
implement issue #187  by adding `fpga_flash f1(f2)` to CLI commands for programming FPGA1(2) from flash.
=> Add CLI command to program FPGA from flash (implement issue #187)

projects/boot_loader/bl_userhooks.c, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/WatchdogTask.c, projects/cm_mcu/commands/SensorControl.c, projects/cm_mcu/commands/SoftwareCommands.c
also get rid of some duplication
removed
- simple_sensor (removed code)
- watchdog task (commented out by `#if 0`)
Before:
```sh
(base) ➜  apollo_cm_mcu git:(master) make -j8  
CC    cm_mcu.c
LD    gcc/cm_mcu.axf 
SZ    gcc/cm_mcu.axf
text	   data	    bss	    dec	    hex	filename
86989	   4628	  45856	 137473	  21901	gcc/cm_mcu.axf
```
After:
```sh
(base) ➜  apollo_cm_mcu git:(cli_help) make -j8 
CC    cm_mcu.c
LD    gcc/cm_mcu.axf 
SZ    gcc/cm_mcu.axf
text	   data	    bss	    dec	    hex	filename
85789	   4628	  45856	 136273	  21451	gcc/cm_mcu.axf
```
text segment reduced by 1200 bytes.
=> Clean up CLI help comments to reduce memory usage

.github/workflows/c-cpp.yml, .github/workflows/codeql-analysis.yml, .github/workflows/format-commit.yml, projects/cm_mcu/CommandLineTask.c, projects/cm_mcu/FreeRTOSConfig.h, projects/cm_mcu/I2CCommunication.h, projects/cm_mcu/LocalTasks.c, projects/cm_mcu/MonitorI2CTask.c, projects/cm_mcu/Semaphore.h, projects/cm_mcu/Tasks.h, projects/cm_mcu/cm_mcu.c, projects/cm_mcu/commands/BoardCommands.c, projects/cm_mcu/commands/SensorControl.c, projects/cm_mcu/commands/SensorControl.h
This set of cleanups was done with in the context of debugging some I2C failures on the new Samtec 12 channel fireflies. That study was ultimately inconclusive. The changes here are 
* add two commands, `ff_reset` and `ff_mux_reset`
* add some documentary comments
* fix a bug where some ADDR_ACK_ERRORS were reported as a semaphore error 
* start removing some globals
=> Various clean-ups

projects/cm_mcu/commands/SensorControl.c
Fix
* fix `ff xmit off all` and `ff recvr off all` commands
* add clearing of i2c mux on `read_ff_register` and `write_ff_register`
=> Hotfix for two CLI Firefly commands

.gitignore, Makefile, make_release_xml_tgz.sh, sm_cm_config/data/address_apollo.xml, sm_cm_config/data/connections.xml
closes #222
when `make release` is called, this will cause a new tgz file to be created that has the right format so it can be installed in `/fw/CM` on the Zynq.
On the zynq:
```
[cms@cmsapollo214 ~]$ tree /fw/CM/CornellCM_MCU/
/fw/CM/CornellCM_MCU/
└── address_table
├── address_apollo.xml
├── address_apollo.xml~
├── connections.xml
├── connections.xml~
└── modules_CM_MCU
├── modules_CM_MCU -> modules_CM_MCU
├── PL_MEM_CM_old.xml
├── PL_MEM_CM_rev2.xml
└── PL_MEM_CM.xml -> PL_MEM_CM_rev2.xml
2 directories, 8 files
```
This PR generates a tgz file as follows:
```
(base) [tmp] tree CornellCM_MCU               11:23:42  ☁  xml_release ☂ ⚡ ✚ ✭
CornellCM_MCU
└── address_table
├── address_apollo.xml
├── connections.xml
└── modules_CM_MCU
├── PL_MEM_CM.xml -> PL_MEM_CM_Rev2.xml
├── …
```
=> add script to generate xml TGZ file

make_release_xml_tgz.sh
with just `#! /bin/sh` I get 
```
SH    make_release_xml_tgz.sh
trap: DEBUG: bad trap
make: *** [Makefile:41: release] Error 1
```
which the [internets suggest](https://stackoverflow.com/questions/11280240/why-my-trap-doesnt-work-when-the-signal-set-as-debug-fake-signal) is from ash not bash being what is invoked as /bin/sh in the github CI runner.
=> choose bash explicitly in release generation sh script

.gitignore, projects/cm_mcu/FireflyUtils.c, projects/cm_mcu/MonitorTask.c, projects/cm_mcu/commands/SensorControl.c
- wrong value which does not fit into 16 bit int for Zynq transmission
- also fix printout of `ff_optpow`
=> fix firefly optical power commands
