apollo-lhc/cm_mcu

.travis.yml
projects/project2/ADCMonitorTask.c
projects/project2/CommandLineTask.c
projects/project2/Makefile
projects/project2/RandomTask.c
projects/project2/project2.c
projects/project2/startup_gcc.c

ADC reading task. Includes 20 power supplies and TM4C internal die temperature. Command line accessible.

Add ADC reading task

---

common/power_ctl.h
projects/project2/CommandLineTask.c
projects/project2/FireFlyTask.c
projects/project2/LedTask.c
projects/project2/PowerSupplyTask.c
projects/project2/Tasks.h
projects/project2/project2.c

* enable or disable CDR on 4 ch XCVR
* enable or disable laser on 4 ch XCVR
Fixes #18

Code cleanup, and some tools to modify SamTec FF registers.

---

projects/cm_mcu/InitTask.c

Eeprom buffer

---

Makefile
projects/Makefile
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/InitTask.c
projects/cm_mcu/Makefile
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/config.h
projects/cm_mcu/microrl.c
projects/cm_mcu/microrl.h

New CLI interface with history, and more robustness.  Also fix problem where travis was not picking up failing builds due to the build order (better makefiles.)

New CLI interface

---

makedefs

promote warnings to error when not on doing a debug build

CI update 

---

projects/cm_mcu/CommandLineTask.c

(cherry picked from commit ba5b2b0bd06c045995572f48a3d7c7b10e37ffba)

fix rollover bug in uptime

---

README.md
common/TM4C129x.pinmux
common/pinout.c
common/pinout.h
common/softuart.c
common/softuart.h
common/summary.csv
makedefs
projects/cm_mcu/ADCMonitorTask.c
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FireFlyTask.c
projects/cm_mcu/InterruptHandlers.c
projects/cm_mcu/InterruptHandlers.h
projects/cm_mcu/LedTask.c
projects/cm_mcu/Makefile
projects/cm_mcu/SoftUartTask.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/startup_gcc.c

for @dgastler and @pwittich testing

Softuart test candidate

---

projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FreeRTOSConfig.h
projects/cm_mcu/Tasks.h
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/startup_gcc.c

* increase the system stack size
* put in a canary into the system stack on boot
* turn on FreeRTOS Idle Hook and use it to monitor changes to the canary
* also add a printout of the high water mark into the CLI

System stack updates

---

.clang-format
.clang-tidy
.gitignore
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FireFlyTask.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/cm_mcu.c

CLI interface to read/write to arbitrary CLI interfaces. 
Closes rest of #54

Write and read from arbitrary FF registers

---

common/power_ctl.c
common/power_ctl.h
common/smbus_units.c
common/utils.c
projects/boot_loader/bl_config.h
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FireFlyTask.c
projects/cm_mcu/FreeRTOSConfig.h
projects/cm_mcu/I2CSlaveTask.c
projects/cm_mcu/LocalTasks.c
projects/cm_mcu/MonitorTask.c
projects/cm_mcu/MonitorTask.h
projects/cm_mcu/PowerSupplyTask.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/startup_gcc.c

- Rewrite of PowerSupplyTask to clean it up
- Code to understand behavior of LGA80D power supply modules. 
note that the LGA80D power supply module code needs a mod to the 3.3V I2C lines on the board and will not work with an un-modded board.

Power supply state machine clean-up and debugging code

---

projects/cm_mcu/I2CCommunication.c
projects/cm_mcu/I2CCommunication.h
projects/cm_mcu/clocksynth.c

Fixing a bug in I2CCommunication that results in some memory overwrite.
Fixing a type discrepancy in clocksynth.c.

Make fixes to I2CCommunication.c and clocksynth.c

---

.github/workflows/c-cpp.yml
.github/workflows/release.yml
common/utils.c
common/utils.h
projects/cm_mcu/LocalTasks.c
projects/cm_mcu/MonitorTask.c
projects/cm_mcu/ZynqMonTask.c
projects/cm_mcu/commands/SensorControl.c

this commit adds the I2C temperature register read for the 2nd SYSMON on the 2nd SLR on the VU7P FPGA.

Ability to read SYSMON in both SLRs in VU7P

---

common/log.h
projects/cm_mcu/LocalTasks.c

* Logger only reports file, not whole path (hack __FILE__)
* fix incorrect labeling of some of the LGA80D supplies
* don't reset RTC on boot

Some minor string improvements

---

common/smbus.c
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FireFlyTask.c
projects/cm_mcu/I2CCommunication.c
projects/cm_mcu/I2CCommunication.h
projects/cm_mcu/commands/I2CCommands.c
projects/cm_mcu/rl_config.h

Fix regression on I2C register reading introduced in #125

Fix regression on I2C register reading

---

common/LocalUart.c
common/log.c
common/log.h
common/utils.c
makedefs
projects/cm_mcu/ADCMonitorTask.c
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/EEPROMTask.c
projects/cm_mcu/FireFlyTask.c
projects/cm_mcu/GenericAlarmTask.c
projects/cm_mcu/I2CCommunication.c
projects/cm_mcu/I2CSlaveTask.c
projects/cm_mcu/LedTask.c
projects/cm_mcu/Makefile
projects/cm_mcu/MonitorTask.c
projects/cm_mcu/PowerSupplyTask.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/WatchdogTask.c
projects/cm_mcu/ZynqMonTask.c
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/commands/BoardCommands.c
projects/cm_mcu/commands/EEPROMCommands.c
projects/cm_mcu/commands/SensorControl.c

Zynq monitoring generalization and updates for Rev2

---

common/log.c
common/log.h
common/utils.c
common/utils.h
projects/cm_mcu/ADCMonitorTask.c
projects/cm_mcu/AlarmUtilities.h
projects/cm_mcu/CommandLineTask.c
projects/cm_mcu/FreeRTOSConfig.h
projects/cm_mcu/I2CSlaveTask.c
projects/cm_mcu/InterruptHandlers.h
projects/cm_mcu/LocalTasks.c
projects/cm_mcu/Makefile
projects/cm_mcu/MonitorI2CTask.c
projects/cm_mcu/MonitorI2CTask.h
projects/cm_mcu/Semaphore.c
projects/cm_mcu/Semaphore.h
projects/cm_mcu/Tasks.h
projects/cm_mcu/ZynqMonTask.c
projects/cm_mcu/clocksynth.h
projects/cm_mcu/cm_mcu.c
projects/cm_mcu/commands/BoardCommands.c
projects/cm_mcu/commands/BoardCommands.h
projects/cm_mcu/startup_clang.c

This PR goes part of the way to addressing issue #140. It creates a function for turning on the bits to enable 3V8 to the 12 Channel FF and a CLI function to call that function.

CLI for turning on 3.8V for power supplies

---

projects/cm_mcu/MonitorI2CTask.c
projects/cm_mcu/cm_mcu.c

Debug apollo214

---

.github/workflows/format-commit.yml
common/log.c
projects/cm_mcu/I2CSlaveTask.c
projects/cm_mcu/cm_mcu.c

Fix bug in the MCU code for the I2C device controller.

I2c device fix

---

projects/cm_mcu/LocalTasks.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/ZynqMonTask.c
projects/cm_mcu/commands/SensorControl.c
projects/cm_mcu/commands/SensorControl.h
sm_cm_config/data/PL_MEM_CM_rev2.yml
sm_cm_config/src/mcu_generate.py
sm_cm_config/src/xml_generate.py

See https://github.com/apollo-lhc/cm_mcu/pull/201#issuecomment-1892829503

Resolve rollover and add ff_laser_fault implemention

---

sm_cm_config/README.md

minor changes from the sm_cm_config, merge back into cm_mcu

Changes from sm_cm_config subtree

---

.github/workflows/release.yml
sm_cm_config/data/PL_MEM_CM_rev2.yml

also fix bug in rev2 yaml file

update release CI action for latest way to get ARM-GCC-NONE-NOABI

---

projects/cm_mcu/ZynqMonTask.c

Putting it here ignores power state.

disable Firefly Tx bit in ZynqmonTask

---

projects/cm_mcu/ZynqMonTask.c
sm_cm_config/data/PL_MEM_CM_rev2.yml

hot fix for FF_ISPRESENT

---

.github/workflows/c-cpp.yml
projects/prod_test/CommandLineTask.c
projects/prod_test/InterruptHandlers.c
projects/prod_test/InterruptHandlers.h
projects/prod_test/Makefile
projects/prod_test/PowerI2CCommands.c
projects/prod_test/PowerI2CCommands.h
projects/prod_test/commands.c
projects/prod_test/commands.h
projects/prod_test/prod_test.c
projects/prod_test/startup_clang.c
projects/prod_test/startup_gcc.c

Added I2C communication test to DC-DC converters, and tested on rev3. There may be hideous style issues due to lack of familiarity with MCU code, just let me know what to fix.

Dcdc i2ctest

---

projects/cm_mcu/startup_gcc.c
projects/prod_test/ADCMonitorTask.c
projects/prod_test/CommandLineTask.c
projects/prod_test/InterruptHandlers.c
projects/prod_test/InterruptHandlers.h
projects/prod_test/Makefile
projects/prod_test/commands.c
projects/prod_test/commands.h
projects/prod_test/prod_test.c
projects/prod_test/startup_gcc.c

wholesale copy from cm_mcu for now.

Enable ADC monitoring in production test

---

.github/workflows/c-cpp.yml
.github/workflows/release.yml
make_release_xml_tgz.sh
projects/cm_mcu/LocalTasks.c

Clean up and test clock from EEPROM in Rev3 (closes #239 and #244)
Clean up some minor issues in release creation.

Release bug fix and EEPROM-based clock loading

---

projects/cm_mcu/InitTask.c
projects/cm_mcu/LocalTasks.c
projects/cm_mcu/PowerSupplyTask.c
projects/cm_mcu/Tasks.h
projects/cm_mcu/clocksynth.c

move clk programming to power supply state machine
